- name: data gathere cvs disk report
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get disk space usage
      command: df -Th
      register: disk_space

    - name: Generate final CSV report using Jinja2 template
      template:
        src: df_report_template.j2
        dest: /tmp/final_disk_usage_report.csv
      delegate_to: localhost
