---
- name: Gather disk usage and write to CSV
  hosts: all
  gather_facts: yes
  tasks:
    - name: Run df -Th command
      shell: df -Th
      register: disk_usage

    - name: Write CSV header
      copy:
        content: "IP,Hostname,Filesystem,Size,Used,Avail,Use%,Mounted on\n"
        dest: "/tmp/disk_usage_report.csv"
        force: no

    - name: Append disk usage to CSV
      lineinfile:
        path: "/tmp/disk_usage_report.csv"
        line: "{{ ansible_host }},{{ ansible_hostname }},{{ item }}"
      loop: "{{ disk_usage.stdout_lines }}"
      when: item not in ["", "Filesystem", "tmpfs"]

    - name: Fetch the CSV file to local
      fetch:
        src: "/tmp/disk_usage_report.csv"
        dest: "./reports/"
        flat: yes
